from cv2 import cv2
from matplotlib import pyplot as plt
img=cv2.imread("Resources/Data/103204.jpg")
laplacian=cv2.Laplacian(img, cv2.CV_64F) 
sobelx=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=5) 
sobely=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=5)
plt.figure(figsize=(11,8))
plt.subplot(231),plt.imshow(img),plt.title('Original')
plt.xticks([]),plt.yticks([])
plt.subplot(232),plt.imshow(laplacian),plt.title('Laplacian')
plt.xticks([]),plt.yticks([])
plt.subplot(234),plt.imshow(sobelx),plt.title('Sobel X')
plt.xticks([]),plt.yticks([])
plt.subplot(235),plt.imshow(sobely),plt.title('Sobel Y')
plt.xticks([]),plt.yticks([])
plt.show() 